- name: Deploy Static Web App
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_CLIFF_0099C9F1E }}
    action: "upload"
    app_location: "/"              # Root folder
    output_location: "/"           # Same as app folder
    skip_app_build: true           # âœ… Skip build step
